require("plugins.lazy")
require("plugins.lsp")
require("plugins.feline-config")
require("plugins.bufferline-config")
require("plugins.nvim-autopair-config")
require("plugins.telescope-config")
require("plugins.neo-tree-config")
require("plugins.nvim-treesitter-config")
