require("plugins.lazy")
require("plugins.lsp")
require("plugins.nvim-tree-config")
require("plugins.feline-config")
require("plugins.nvim-treesitter-config")
require("plugins.bufferline-config")
require("plugins.nvim-autopair-config")
