require("plugins.plugin-manager")
require("plugins.nvim-tree-config")
require("plugins.lualine-config")
require("plugins.bufferline-config")
require("plugins.telescope-config")
require("plugins.lsp-config")
